### ISSUE TITLE
locale how to use

### ISSUE THREAD

**Issue by luohong123** [mattlewis92/angularx-flatpickr#10]
hello ,I use anguar4 ,for example,
`//时间、时分秒、时间区间
import { FlatpickrModule, FLATPICKR } from 'angularx-flatpickr';
import * as flatpickr from 'flatpickr';
import "flatpickr/dist/l10n/zh.js";`
 but not working

**Comment by mattlewis92** [comment]
You need to pass the locale through to the [locale input](https://mattlewis92.github.io/angularx-flatpickr/docs/directives/FlatpickrDirective.html#locale) of flatpickr. You can see how to import the locale here: https://chmln.github.io/flatpickr/localization/
