### ISSUE TITLE
TypeError: this.flatpickr is not a function

### ISSUE THREAD

**Issue by jebbench** [mattlewis92/angularx-flatpickr#12]
Hello,

Trying to use this in an Angular 5 project but I'm getting the error below.
```
ERROR TypeError: this.flatpickr is not a function
    at FlatpickrDirective.ngAfterViewInit (angularx-flatpickr.js:282)
    at callProviderLifecycles (core.js:12691)
    at callElementProvidersLifecycles (core.js:12658)
    at callLifecycleHooksChildrenFirst (core.js:12641)
    at checkAndUpdateView (core.js:13796)
    at callViewAction (core.js:14138)
    at execComponentViewsAction (core.js:14070)
    at checkAndUpdateView (core.js:13793)
    at callViewAction (core.js:14138)
    at execComponentViewsAction (core.js:14070)
```

I'm trying to use it with Reactive forms - is the below correct?
```
<input class="input" mwlFlatpickr type="text" placeholder="" formControlName="open">
```

app.module.ts
```
...;
import {FLATPICKR, FlatpickrModule} from "angularx-flatpickr";
import * as flatpickr from "flatpickr";

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    ...,
    FlatpickrModule.forRoot({
      provide: FLATPICKR,
      useFactory: flatpickrFactory
    })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

export function flatpickrFactory() {
  return flatpickr;
}
```

Module where I'm trying to use the date picker:
```
...
import {FlatpickrModule} from "angularx-flatpickr";

@NgModule({
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FlatpickrModule
  ],
  declarations: [...],
  exports: [DashboardComponent]
})
export class AdminModule { }
```

Cheers,
JB

**Comment by mattlewis92** [comment]
Flatpickr recently updated their default export which broke the import, if you change
```
import * as flatpickr from "flatpickr";
```

to 

```
import flatpickr from "flatpickr";
```

It should work. I will leave this issue open as a reminder to fix it in the docs and example code.

**Comment by jebbench** [comment]
Okay... now I'm confused; I must have something configured wrong in my build somewhere.

If i do the following:
`import * as flatpickr from "flatpickr";`
`ng serve`
test - I get the error "ERROR TypeError: this.flatpickr is not a function"
Change the import to `import flatpickr from "flatpickr";`
ng serve (without restarting) states: "ERROR in src/app/app.module.ts(17,8): error TS1192: Module '"c:/project/node_modules/flatpickr/index"' has no default export."
test (without restarting ng serve) - works as expected.
restart `ng serve`
refuses to compile stating "ERROR in src/app/app.module.ts(17,8): error TS1192: Module '"C:/Users/james/Code/fisheries-ng/node_modules/flatpickr/index"' has no default export."

IntelliJ also doesn't like the  `import flatpickr from "flatpickr";` but looking at the flatpickr module in node_modules it looks like it does export a default to me.

**Comment by mattlewis92** [comment]
Are you on version `4.2.3` on flatpickr? They only just fixed their typings to be correct.

**Comment by jebbench** [comment]
Yeah - I was using 4.2.3

**Comment by mattlewis92** [comment]
Ah, maybe the typings are still wrong. Does setting `"allowSyntheticDefaultImports": true` in your `tsconfig.json` fix it? I'll try and cut a new major soon that just does the import for you so you shouldn't see these issues again in v6+

**Comment by jebbench** [comment]
`"allowSyntheticDefaultImports": true` in tsconfig.json does indeed fix it thanks.

**Comment by mredl** [comment]
`"allowSyntheticDefaultImports": true` and `import flatpickr from 'flatpickr';` fixed it for me in an aurelia ts project. thanks

**Comment by mattlewis92** [comment]
Fixed by https://github.com/mattlewis92/angularx-flatpickr/commit/45e2d3d390f2019da01032f322e269e51e1fee81
