### ISSUE TITLE
Date time picker doesn't work in Safari on macOS

### ISSUE THREAD

**Issue by Schaemelhout** [mattlewis92/angularx-flatpickr#13]
This is easily reproducible on the demo page:
https://mattlewis92.github.io/angularx-flatpickr/

The DateTime picker keeps returning an invalid date...

**Comment by mattlewis92** [comment]
Ah, looks like safari doesn't like the space in between the date and time, adding a `T` in between them seems to do the trick. Thanks for reporting! 😄
