### ISSUE TITLE
How can I bind a function to (onChange)?

### ISSUE THREAD

**Issue by march23hare** [mattlewis92/angularx-flatpickr#14]
How can I bind a function to (onChange)?
Could you plz show me codes for example?
I've read the Method section of the document but I can't understand it...

**Comment by mattlewis92** [comment]
Please see the tests for an example of how you can trigger an event when the value changes: https://github.com/mattlewis92/angularx-flatpickr/blob/master/test/flatpickr.directive.spec.ts#L53

Hope that helps! 😄
