### ISSUE TITLE
Can't set locale different than "en"

### ISSUE THREAD

**Issue by monoteos** [mattlewis92/angularx-flatpickr#3]
flatpickr: invalid locale jp

template: ` 
  <input mwlFlatpickr 
  [locale]="'jp'"
  [enableTime]="enableTime" 
  [enableSeconds]="enableSeconds"
  [altInput]="true" 
  [dateFormat]="'Y-m-d H:i:S'" 
  [altFormat]="dateFormat"
  [convertModelValue]="true" 
  type="text" >`

**Comment by mattlewis92** [comment]
It looks like you need to load the locale file for i18n to work: https://github.com/chmln/flatpickr/issues/406#issuecomment-260845764

**Comment by guillaumegarcia13** [comment]
Thus can be done this way for French:
```
import { FlatpickrModule, FLATPICKR } from 'angularx-flatpickr';
import Flatpickr from 'flatpickr';
import FlatpickrL10N_fr from 'flatpickr/dist/l10n/fr';

export function flatpickrFactory() {
    Flatpickr.localize(FlatpickrL10N_fr.fr);
    return Flatpickr;
}
```

**Comment by joaomantovani** [comment]
Just a complement:

Create the export function above and add the function `flatpickrFactory();` to your component.ts `ngOnInit()`.

```
ngOnInit() {
  flatpickrFactory();
  // Your other logic here...
} 
```

And in your component.html (templateUrl), add the directive, like this example:

```
<input 
  type="text" 
  mwlFlatpickr 
  [(ngModel)]="selectedDate" 
  [altInput]="true" 
  [dateFormat]="'d.m.y'"
  [locale]="'Portuguese'"
  [convertModelValue]="true
```

**Comment by isma907** [comment]
**The correct way to translate the FlatPickr is:**

### NgModule file:
import { FlatpickrModule } from 'angularx-flatpickr';
import { Spanish } from 'flatpickr/dist/l10n/es.js';

`
@NgModule({
  declarations: [ ...  ],
  imports: [
         FlatpickrModule.forRoot({
            locale: Spanish
     }),
  ]
`


### Component Html File:
` 
<input class="form-control" type="text" mwlFlatpickr
                                    [formControl]="myControl" [enableTime]="true"
                                    [dateFormat]="'d/m/y H:i'">
`


![image](https://user-images.githubusercontent.com/7232299/69346224-376d0f80-0c51-11ea-814a-639eb9518c44.png)

**Comment by DIM29** [comment]
> 
> 
> **The correct way to translate the FlatPickr is:**
> ### NgModule file:
> 
> import { FlatpickrModule } from 'angularx-flatpickr';
> import { Spanish } from 'flatpickr/dist/l10n/es.js';
> 
> `@NgModule({ declarations: [ ... ], imports: [ FlatpickrModule.forRoot({ locale: Spanish }), ]`
> ### Component Html File:
> 
> ` <input class="form-control" type="text" mwlFlatpickr [formControl]="myControl" [enableTime]="true" [dateFormat]="'d/m/y H:i'">`
> 
> ![image](https://user-images.githubusercontent.com/7232299/69346224-376d0f80-0c51-11ea-814a-639eb9518c44.png)

thank you so much
