### ISSUE TITLE
get started demo fail

### ISSUE THREAD

**Issue by xg-wang** [mattlewis92/angularx-flatpickr#4]
```
@angular/cli: 1.4.2
node: 8.6.0
os: darwin x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.4
@angular/language-service: 4.4.4
typescript: 2.3.4
```

`"angularx-flatpickr": "^2.0.1"`

Just import `FlatpickrModule.forRoot()` in app.module and copy pasted the demo-component.
The error message is 
`TypeError: Cannot read property 'nodeType' of null` and `TypeError: this.instance.setDate is not a function`.

**Comment by mattlewis92** [comment]
Please give 3.0.0 a try, @eyalhakim was kind enough to provide a fix for this :octocat:
