### ISSUE TITLE
Not get form-control class into <input> after update  "flatpickr"  package > 4.5.7  

### ISSUE THREAD

**Issue by specchiasoft** [mattlewis92/angularx-flatpickr#40]
I have upgraded all packages to angular 9  "angularx-flatpickr": "6.3.0", "flatpickr": "4.6.3";

After this the < input >  box is not well formatted , the issue is introduced after "flatpicker" pakage >= 4.6.0 ;  with  "flatpickr" 4.5.7 works well. 

flatpicker version 4.6.3
 `<input class="" placeholder="date?" tabindex="0" type="text" readonly="readonly">` 

flatpicker before 4.6.0
`<input class="form-control ng-untouched ng-pristine ng-valid flatpickr-input active" placeholder="date?" tabindex="0" type="text" readonly="readonly">`

Thank you for your job i use also your magnific Calendar!.

**Comment by mattlewis92** [comment]
Hey there,

Unfortunately I wasn't able to reproduce your issue: https://stackblitz.com/edit/angular-radxk3?file=src%2Fapp%2Fapp.component.html

If you can put together a minimal repro that shows your issue then I'd be happy to debug further. Thanks! 😄

**Comment by mattlewis92** [comment]
Ahh, I found the issue, it's a bug in flatpickr: https://github.com/flatpickr/flatpickr/issues/1860

I can fix it here pretty easily though, will be fixed in `6.3.1` 🎉
