### ISSUE TITLE
Does not work with standalone components

### ISSUE THREAD

**Issue by mohamed155** [mattlewis92/angularx-flatpickr#57]
### Describe the bug

This package is not designed to work with standalone components

### Minimal reproduction of the problem with instructions

Try to import the module in a standalone component, and you will get a NullInjectorError.

### @angular/core version

19

### angularx-flatpickr version

8

### Browser name and version

Brave 1.73.91

**Comment by aparzi** [comment]
Duplicate #56.

**Comment by mattlewis92** [comment]
Please give `8.1.0` a go, the project was converted to standalone and you can now do:
```
imports: [FlatpickrDirective],
providers: [provideFlatpickrDefaults()],
```

in your component!

**Comment by maierfabian** [comment]
Does work now thanks. Bdw how can I style the select or?
