### ISSUE TITLE
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.

### ISSUE THREAD

**Issue by eyalhakim** [mattlewis92/angularx-flatpickr#6]
Happens when using formControlName directive.

**Comment by mattlewis92** [comment]
Any repro? It works in the tests: https://github.com/mattlewis92/angularx-flatpickr/blob/master/test/flatpickr.directive.spec.ts

**Comment by eyalhakim** [comment]
From the link you sent, the test uses ngModel and not formControl. Do you have an online environment (stackblitz etc.) with the library? I can give it a try

**Comment by mattlewis92** [comment]
The second component uses a form control, you can probably copy / paste it into stackblitz

**Comment by eyalhakim** [comment]
getting a strange error from the import in the app.module:
https://stackblitz.com/edit/angular-qq1pc9?file=app%2Fapp.module.ts

do you know why?

Thanks

**Comment by mattlewis92** [comment]
It looks like the issue is with the flatpickr import + system.js, if you change 

```
import * as flatpickr from 'flatpickr';
```
to
```
import flatpickr from 'flatpickr';
```

then it works

**Comment by eyalhakim** [comment]
i think it happens to me because i'm using the directive in a separate route.
When loading this route directly, everything works, but when navigating to it, i get this error.

Can you try reproduce?
Also, i'm using it with Angular Material, i don't think it has something to do with it but maybe...

**Comment by mattlewis92** [comment]
I'm afraid without a clear way of reproducing it, it's impossible for me to help any further 😞  LMK if you manage to find a way to reproduce it outside of your app and I'd be happy to help more!

**Comment by eyalhakim** [comment]
do you know what the problem is here?:
https://stackblitz.com/edit/angular-gjqfw4?file=app%2Fhello.component.ts

**Comment by mattlewis92** [comment]
It looks like the flatpickr styles aren't imported.

**Comment by eyalhakim** [comment]
your'e right, i did notice it.
However, they also weren't imported on the last two repos we shared with each other, were they?

**Comment by mattlewis92** [comment]
You have to add the flatpickr stylesheet in the left hand side like so: https://stackblitz.com/edit/angular-cjyfxf?file=app/app.component.css
