### ISSUE TITLE
zone.js:657 TypeError: this.flatpickr is not a function

### ISSUE THREAD

**Issue by eyalhakim** [mattlewis92/angularx-flatpickr#7]
zone.js:657 TypeError: this.flatpickr is not a function
    at FlatpickrDirective.webpackJsonp.../../../../angularx-flatpickr/flatpickr.directive.js.FlatpickrDirective.ngAfterViewInit

Is thrown when compiling with AOT.

**Comment by mattlewis92** [comment]
It sounds like you're transpiling your code to commonjs in JiT mode, but es2015 modules in AoT module. Meaning:
```
// only works in Jit mode, fails in AoT
import * as flatpickr from 'flatpickr';
```

```
// only works in AoT mode, fails in JiT
import flatpickr from 'flatpickr';
```

You can workaround it by making sure your typescript module option is always set to `es2015` for JiT mode and then doing  `import flatpickr from 'flatpickr';`, alternatively you can require flatpickr by doing `const flatpickr = require('flatpickr');`

**Comment by eyalhakim** [comment]
@mattlewis92 actually, i changed my imports to
`import flatpickr from 'flatpickr';`

and it still only works in jit mode and not in aot mode.

**Comment by mattlewis92** [comment]
What about if you do `const flatpickr = require('flatpickr');` ?

**Comment by eyalhakim** [comment]
Cannot find name 'require', i am targeting ES2015 btw..

also, i tried to place a console.log(flatpickr) right after the import and it did log a function.
Maybe the bug with the directive is something else?

**Comment by eyalhakim** [comment]
this is what i see in the log:
`ƒ (selector, config) {
    if (selector instanceof NodeList)
        return _flatpickr(selector, config);
    else if (typeof selector === "string")
        return _flatpickr(window.document.queryS…`

**Comment by mattlewis92** [comment]
hmm that looks correct, are you able to share a way of reproducing the problem?

**Comment by eyalhakim** [comment]
i can give you access to my computer using teamviewer if you are willing to

**Comment by mattlewis92** [comment]
Sorry I don't have the time for that, a minimal runnable repo would be perfect though

**Comment by eyalhakim** [comment]
i understand, do you know how to run aot using stackblitz or any other cloud service?
Also, i commented on the other issue with a repo that doesn't work for me, maybe we can start there.

**Comment by mattlewis92** [comment]
I don't think its possible to do AoT in the browser as it requires node to do the compilation. Your best bet is making a blank repo on github and the cli to scaffold out the project.

**Comment by eyalhakim** [comment]
okay, i did some more digging and apparently the forRoot function is not called with aot!

any idea?

**Comment by mattlewis92** [comment]
That’s odd, it’s the pattern I use successfully across all my projects

**Comment by eyalhakim** [comment]
updates:
1.
forRoot was not called on runtime (doh, aot) but i changed it to 
`
let bla = FlatpickrModule.forRoot(flatpickr);
`

and then import bla, and it is called;

2.
even if i provide {} to the forRoot function
`
FlatpickrModule.forRoot({});
`
it is still null in the directive.
Furthermore, even if i hard code
`
 return {
            ngModule: FlatpickrModule,
            providers: [
                {
                    provide: FLATPICKR,
                    useValue: {}
                },
...
`
it is still null in the directive.

3.
when trying to inject FLATPICKR directly into one of my components, it is still null.

Any Ideas?

**Comment by mattlewis92** [comment]
Please give 4.0.0 a go, I think I've fixed it

**Comment by eyalhakim** [comment]
@mattlewis92 works perfect!
i am using a short syntax that you might want to include in the readme:
`
FlatpickrModule.forRoot({
      provide: FLATPICKR,
      useFactory: () => flatpickr
    }),
`

thank you!

**Comment by mattlewis92** [comment]
That’s great to hear 😀
