### ISSUE TITLE
Error in options.ts DateLimit and DateRangeLimit requres 2 type argument(s)

### ISSUE THREAD

**Issue by Ukiand1** [mattlewis92/angularx-flatpickr#9]
When I just add it to NgModule into my Angular 5 project and try to "ng serve" I receive this error. Is it a known error because I don't want to mess with it manually?

### Error that I get
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/src/types/options.ts (6,30): ',' expected.
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/src/types/options.ts (7,25): ',' expected.
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/src/types/options.ts (9,5): Generic type 'DateRangeLimit' requires 2 type argument(s).
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/src/types/options.ts (95,13): Generic type 'DateLimit' requires 2 type argument(s).
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/src/types/options.ts (102,12): Generic type 'DateLimit' requires 2 type argument(s).
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/src/types/options.ts (221,13): Generic type 'DateLimit' requires 2 type argument(s).
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/src/types/options.ts (222,12): Generic type 'DateLimit' requires 2 type argument(s).
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/src/types/options.ts (240,12): Generic type 'DateLimit' requires 2 type argument(s).
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/src/types/options.ts (242,11): Generic type 'DateLimit' requires 2 type argument(s).
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/index.d.ts (32,29): Generic type 'DateLimit' requires 2 type argument(s).
ERROR in /Users/uros/Desktop/untitled folder 3/backend-doc/node_modules/flatpickr/index.d.ts (34,34): Generic type 'DateRangeLimit' requires 2 type argument(s).

## Environment
flatpickr version 4.1.2
macOS

**Comment by mattlewis92** [comment]
I use this in angular 5 project + with v `4.1.2` of flatpickr and don't get these errors. They all come from `flatpickr` and not this library so you should raise the issue there.

**Comment by Ukiand1** [comment]
Okay, thanks for the quick answer!
